apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: exampleshop-prod
spec:
  serviceName: kafka-service
  replicas: 3  
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"   #in prod, topics are created explicitly
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 20Gi